### ISSUE TITLE
really cool _ issue with html

### ISSUE THREAD

**Issue by pixeline** [Nyl000/NylAutoWriter#1]
Thank you for this nice text effect. There is an issue when the content contains some html (an anchor for instance). It seems to process it as text, thus "hanging" weirdly until all the html code has been parsed.

**Comment by Nyl000** [comment]
Hi ! 
Thanks for your issue and for using my plugin !
I see what you mean and I noticed this glitch already. But it's tricky to "catch" html tags and re-render them as long as the string is rendered letter by letter. 
That would be a great challenge to code a renderer for that case.. Maybe several instances launched one by one on the text content of html nodes found inside the wrapper. 
I'll think about it..

**Comment by pixeline** [comment]
I started to explore the problem, and I think you could detect html when you create the array via split('');

Here is how it is done in typed.js : https://github.com/mattboldt/typed.js/blob/master/js/typed.js#L179

**Comment by Nyl000** [comment]
Thanks, your example is working here too :) https://github.com/Nyl000/NylAutoWriter/commit/834adb6a83f23014dcca631637c246116d4f89bb
